### ISSUE TITLE
SwissHouseRSlaTank-v0 return NoneType

### ISSUE THREAD

**Issue by filippobertolotti0** [bsl546/energym#11]
hi! trying the code copied by the notebook example into the documentation of SwissHouseRSlaTank-v0 model i found an error. The compilation return the following error:
AttributeError: 'NoneType' object has no attribute 'get_inputs_names'.

Seems that it can't build the environment correctly. i've tried other models, and all of them work properly.

**Following, the full error log:**

Unable to build model. Failed to validate modelDescription.xml:
- The combination causality="local" and variability="constant" in variable "heaPum.eva.port_b.p" (line 1684) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.preDro.port_b.p" (line 1792) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.medium.p" (line 2072) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.medium.state.p" (line 2100) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.p_start" (line 2112) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.ports[1].p" (line 2128) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.ports[2].p" (line 2144) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.p" (line 2280) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.p_start" (line 2284) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.ports[1].p" (line 2304) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.ports[2].p" (line 2320) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.state_start.p" (line 2380) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.port_b2.p" (line 2500) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.staB2.p" (line 2552) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.sta_b2.p" (line 2600) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.state_b2_inflow.p" (line 2648) is not allowed.
- The combination causality="local" and variability="constant" in variable "hole.p_in_internal" (line 2736) is not allowed.
- The combination causality="local" and variability="constant" in variable "hole.ports[1].p" (line 2752) is not allowed.
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\energym-0.1-py3.11.egg\energym\factory.py", line 570, in make
    return SwissHouse(
           ^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\energym-0.1-py3.11.egg\energym\envs\swiss_house\swiss_house.py", line 261, in __init__
    super().__init__(
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\energym-0.1-py3.11.egg\energym\envs\env_fmu_mod.py", line 131, in __init__
    super().__init__(
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\energym-0.1-py3.11.egg\energym\envs\env_fmu.py", line 159, in __init__
    self.model_description = read_model_description(self.fmu_file)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\fmpy-0.3.20-py3.11.egg\fmpy\model_description.py", line 889, in read_model_description
    raise ValidationError(problems)
fmpy.model_description.ValidationError: Failed to validate modelDescription.xml:
- The combination causality="local" and variability="constant" in variable "heaPum.eva.port_b.p" (line 1684) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.preDro.port_b.p" (line 1792) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.medium.p" (line 2072) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.medium.state.p" (line 2100) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.p_start" (line 2112) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.ports[1].p" (line 2128) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.dynBal.ports[2].p" (line 2144) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.p" (line 2280) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.p_start" (line 2284) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.ports[1].p" (line 2304) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.ports[2].p" (line 2320) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.eva.vol.state_start.p" (line 2380) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.port_b2.p" (line 2500) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.staB2.p" (line 2552) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.sta_b2.p" (line 2600) is not allowed.
- The combination causality="local" and variability="constant" in variable "heaPum.state_b2_inflow.p" (line 2648) is not allowed.
- The combination causality="local" and variability="constant" in variable "hole.p_in_internal" (line 2736) is not allowed.
- The combination causality="local" and variability="constant" in variable "hole.ports[1].p" (line 2752) is not allowed.
Traceback (most recent call last):
  File "c:\Users\filip\Desktop\politecnico\tesi\EnerGym\SwissHouseRSlTank.py", line 6, in <module>
    inputs = env.get_inputs_names()
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_inputs_names'

**The code:**

import energym
weather = "CH_BS_Basel"
env = energym.make("SwissHouseRSlaTank-v0", weather=weather, simulation_days=20)
inputs = env.get_inputs_names()
outputs = env.get_outputs_names()
print("inputs:", inputs)
print("outputs:", outputs)

thanks in advance.
Filippo

**Comment by psh987** [comment]
Hi Filippo,
Sorry for the late response. I tried to reproduce the error on my side, but your code seems to work fine for me. Does the error also occur for other models, especially Modelica based ones, or only for "SwissHouseRSlaTank-v0"?
I am not sure if it could be related to that, but it seems like you have FMPy version 0.3.20 installed, whereas in the [requirements](https://github.com/bsl546/energym/blob/master/requirements.txt), version 0.2.14 is requested. You could try if using the package versions specified in the requirements solves the issue.

**Comment by filippobertolotti0** [comment]
It works properly after the installation of  the correct version of FMPy 4. thank you for the support!
